% Table2: prior densities and posterior estimates of the DSGE model's
% parameters (table 2 of the paper). Reports, for each parameter, the
% prior density (N = Normal, G = Gamma, B = Beta, IG1 = Inverse-Gamma-1),
% its mean and standard deviation, and the posterior mode, median and
% 90% credible interval [5, 95], computed from the MCMC chain in
% draws/DSGE_draws.mat.

close all
clear

S = load(fullfile('draws','DSGE_draws.mat'), 'POSTMODE','P1','N');
Ppost = S.P1(S.N+1:end, :);   % discard the burn-in

% column index into POSTMODE/P1 (bounds.m's parameter order), density,
% prior mean, prior std, parameter symbol, description -- in table 2's
% own row order
rows = { ...
    1,  'N',   0.45,  0.05, '100*gamma',    'steady-state growth rate'; ...
    3,  'G',   0.25,  0.10, '100*(beta^-1-1)', 'discount factor'; ...
    4,  'B',   0.50,  0.10, 'h',            'habit formation'; ...
    5,  'B',   0.66,  0.10, 'xi',           'price stickiness'; ...
    17, 'B',   0.50,  0.10, 'iota',         'price indexation'; ...
    6,  'N',   1.50,  0.50, 'phi_pi',       'response to inflation'; ...
    7,  'N',   0.125, 0.075,'phi_Y',        'response to output gap'; ...
    18, 'N',   0.125, 0.075,'phi_dY',       'response to output-gap growth'; ...
    8,  'B',   0.60,  0.20, 'rho_R',        'interest-rate smoothing'; ...
    9,  'B',   0.40,  0.20, 'rho_z',        'technology growth'; ...
    10, 'B',   0.60,  0.20, 'rho_theta',    'cost-push'; ...
    11, 'B',   0.60,  0.20, 'rho_b',        'preference'; ...
    20, 'N',   1.00,  0.25, 'delta',        'anticipated-shock decay'; ...
    12, 'IG1', 0.15,  1,    '100*sigma_R',  'monetary policy'; ...
    13, 'IG1', 1,     1,    '100*sigma_z',  'technology growth'; ...
    14, 'IG1', 0.15,  1,    '100*sigma_theta', 'cost-push'; ...
    15, 'IG1', 0.025, 1,    '100*sigma_star',  'inflation target'; ...
    16, 'IG1', 1,     1,    '100*sigma_b',  'preference'; ...
    19, 'IG1', 0.15,  1,    '100*sigma_R1', 'anticipated monetary policy' ...
};

outfile = fullfile('results','Table2.csv');
fid = fopen(outfile, 'w');
fprintf(fid, 'Parameter,Description,Density,Prior mean,Prior std,Posterior mode,Posterior median,Posterior 5%%,Posterior 95%%\n');
for r = 1:size(rows,1)
    col = rows{r,1};
    mode   = S.POSTMODE(col);
    draws  = Ppost(:,col);
    med    = median(draws);
    p5     = prctile(draws, 5);
    p95    = prctile(draws, 95);
    fprintf(fid, '%s,%s,%s,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f\n', ...
            rows{r,5}, rows{r,6}, rows{r,2}, rows{r,3}, rows{r,4}, mode, med, p5, p95);
    fprintf('%-16s mode %.4f  median %.4f  [%.4f, %.4f]\n', rows{r,5}, mode, med, p5, p95);
end
fclose(fid);

fprintf('Table2: wrote %s\n', outfile);

% -------------------------------------------------------------------------
% Part of the replication code for Domenico Giannone and Giorgio E.
% Primiceri (2026), "Demand Driven Inflation", Brookings Papers on
% Economic Activity.
%
% Feel free to use and adapt this code for your own research. If it
% contributes to your work, we kindly ask that you acknowledge it by
% citing the accompanying paper.
% -------------------------------------------------------------------------
